### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Rancid1989** [ketwaroo/KetwarooPortiaMod#2]
Hello!

First of all, thank you for your mod!

Second, i have a question. I had an old save where i unlocked the DLCs with a tool similar to yours (Can't remember the name), and can't load the save using the EGS version of My Time at Portia. It says i am missing a DLC even tho i enabled all the ones in your mod.

I enabled your mod, and it appears to unlock the kickstarter1,2,3... dlcs, but apparently, there is one i am missing, kickstarter dlc with no number (All the others work perfectly!).

Is there a way to enable that one too? I have all the dots on the options of your mod marked.

Or, could you add this dlc to the mod? Please? I really don't wanna start over.

If so, thanks a lot. If you are not up to it, i understad. Still again thanks for providing these tools.

Have a nice day!

**Comment by ketwaroo** [comment]
ah sorry. I only have the gog.com version of the game. It's the only version of the game where the DLC weren't even available for purchase.

The content is already there and the mod only flips some bits around in the code. They may not be applicable to the EGS version.

**Comment by Rancid1989** [comment]
> ah sorry. I only have the gog.com version of the game. It's the only version of the game where the DLC weren't even available for purchase.
> 
> The content is already there and the mod only flips some bits around in the code. They may not be applicable to the EGS version.

But your mod works perfectly for my version! It just seems that there is one more mod that apparently your mod doesn't enable. But the mod itself works like a charm!

I was just wondering if you would be able to add that one DLC.

**Comment by ketwaroo** [comment]
it's been a while since I played that game. 

Looking at
https://github.com/ketwaroo/KetwarooPortiaMod/blob/master/KetwarooPortiaModEnableDlc/EnableDlc.cs#L65 I found 8 DLC flags to enable in the code. At least for the gog.com version. Might be more for other versions of the game.

There was one extra called `Max` but that just caused the game to crash on my end so I never enabled it.

Officially, there were 5 kickstater DLC and 3 outfit DLC. There's a console version only DLC too but I don't think that one is available to the PC version.

what's the name of the DLC? what does it contain?

**Comment by Rancid1989** [comment]
I uploaded the screenshots here: https://imgur.com/a/zsoLalh

As i said, it's from a long time ago save so i'm not 100% sure. I believe it has to do with the helmet the avatar is using or the clothes. It came alongside the stuff your mod enables.

**Comment by ketwaroo** [comment]
![Untitled](https://github.com/ketwaroo/KetwarooPortiaMod/assets/608793/80c21976-8128-4a45-82f1-863570a918e6)
So apparently I still had the game installed. I checked real quick and it seems the one labeled  just "Kickstarter Rewards" is actually just the lousy tshirt DLC.

You'll need to enable the DLC via the mod config. See this other comment https://github.com/ketwaroo/KetwarooPortiaMod/issues/1#issuecomment-974757353 for some instructions.

![Uploading image.png…]()

**Comment by Rancid1989** [comment]
I tried that, and i indeed got the shirt in game, and the "tick" appears on the dlc... but can't still load the save game for the same reason than before.

Aah, well. Anyway. I don't want to bother you anymore with this, i thought this would been simpler as just enabling one extra DLC, and i wasted enough of your time. Thanks a lot for trying to help me there, i really appreaciate it. Will just start a new game with your mod.

Take care!

**Comment by ketwaroo** [comment]
No worries, happy to help. Or at least try to help.

My mods are probably a bit unsafe and definitely not tested by a lot of people. That's why I don't publish them on nexsus mods and the like. There's always a chance you can mess up your save game when using any mods though.
